config/routes.rb
Rails.application.routes.draw do
  get 'passengers/new'
  get 'passengers/create'
  get 'bookings/new'
  get 'bookings/create'
  get 'flights/index'
  root "flights#index"

  resources :flights, only: [:index]
  resources :bookings, only: [:new, :create, :show]
  resources :passengers, only: [:new, :create]
  
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, class_name: 'Flight', foreign_key: 'departure_airport_id'
  has_many :arriving_flights, class_name: 'Flight', foreign_key: 'destination_airport_id'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers, inverse_of: :booking

  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, class_name: 'Airport', foreign_key: 'departure_airport_id'
  belongs_to :destination_airport, class_name: 'Airport', foreign_key: 'destination_airport_id'
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
end

app/controllers/airport_controller.rb
class AirportController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  
  def new
    @booking = Booking.new
    #(params[:seats].to_i).times {@booking.passengers.build} 
    @booking.passengers.build #booking.passengers.build builds the passengers instantiated with the booking_id that you are creating now(but it was not yet created). This way the passenger that you create will inherit the booking_id from the booking that you are creating with the form 
    @flight = Flight.find_by(id: params[:flight_id])
    @seats = params[:seats].to_i
  end

  def create
    @booking = Booking.new(booking_params)
    @flight = Flight.find_by(id: params[:flight_id])
    @seats = params[:seats].to_i
    if @booking.save
      redirect_to @booking
    else
      flash.now[:alert] = "Something went wrong"
      render :new
    end
  end

  def show
    @booking = Booking.find_by(id: params[:id])
  end

  private
  def booking_params
    params.require(:booking).permit(:flight_id, :email, :billing, passengers_attributes: [:name, :surname, :booking_id])
  end

end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @airport_options = Airport.all.map { |airport| [airport.code, airport.id] } #this line of code maps the airports so you can use it in the dropdown menu in the #index
    
      if params.has_key?(:departure_airport_id) && params.has_key?(:destination_airport_id) #this is necessary so if the params does not have any key (so the user has not given anything to search for), then the available flights will not be rendering in the index 
        if params[:departure_airport_id] == "" && params[:destination_airport_id] == ""
          flash.now[:alert] = "Please insert departure and destination airport"
        elsif params[:departure_airport_id] == ""
          flash.now[:alert] = "Please insert departure airport"
        elsif params[:destination_airport_id] == ""
          flash.now[:alert] = "Please insert destination airport"
        else
          if params[:date] != "" #date gets deleted from params if it is empty, so if the user doesnt input the date he can see all the flights to the selected airportts that will take place in the future
            @available_flights = Flight.where(flight_params)
          else
            params.delete(:date)
            @available_flights = Flight.where(flight_params)
          end
        end  
      #@available_flights = Flight.where(departure_airport_: params[:departure_airport_], destination_airport_id: params[:destination_airport_id], datetime: params[:datetime])
      #@flight_search = Flight.search(params[:flight])
      #@flight_options = Flight.all.map { |a| [ a.departing_airport.code, a.departing_airport.id ] }.uniq
    end
  end

  private
  def flight_params
    params.permit(:departure_airport_id, :destination_airport_id, :date, :seats)
  end

end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
  def new
  end

  def create
  end
end

app/helpers/airport_helper.rb
module AirportHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/views/bookings/new.html.erb
<h1>Fill the information for your flight</h1>
<p>
  From: <%= @flight.departure_airport.code %> | 
  To: <%= @flight.destination_airport.code %> | 
  Flight duration: <%= @flight.flight_duration %> min | 
  Date: <%= @flight.date.to_date %>
</p>

<%= form_with model: @booking do |f| %>
  <h2>Contact and billing information</h2>
  <% flash.each do |type, msg| %>
    <div style="color:red">
      <%= msg %>
    </div>
    <br>
  <% end %>
  <%= f.label :email, 'Email: ' %>
  <%= f.text_field :email %> |
  <%= f.label :billing, 'Billing: ' %>
  <%= f.number_field :billing %>
  <%= f.hidden_field :flight_id, :value => params[:flight_id] %>
  <%= hidden_field_tag('flight_id', params[:flight_id]) %>
  <%= hidden_field_tag('seats', params[:seats]) %>
  <% @seats.times do |i| %>
    <h2>Passenger <%= i+1 %></h2>
    <%= f.fields_for :passengers do |passenger_attributes| %>
      <%= passenger_attributes.label :name, 'Name: ' %>
      <%= passenger_attributes.text_field :name %> |
      <%= passenger_attributes.label :surname, 'Surname: ' %>
      <%= passenger_attributes.text_field :surname %>
    <% end %>
  <% end %>
  <br><br><br>
  <%= f.submit %>
<% end %>

app/views/bookings/show.html.erb
<h1>Success!</h1>
<h2>You booked your flight</h2>
<p>
  From: <%= @booking.flight.departure_airport.code %> |
  To: <%= @booking.flight.destination_airport.code %> |
  Flight duration: <%= @booking.flight.flight_duration %> min |
  Date: <%= @booking.flight.date.to_date %>
</p>

<h2>Billing and email</h2>
<p>
  Email: <%= @booking.email %> |
  Billing: <%= @booking.billing %>
</p>

<% @booking.passengers.each_with_index do |f, index| %>
    <h2>Passenger <%= index+1 %></h2>
    <p>
      Name: <%= f.name %> |
      Surname: <%= f.surname %>
    </p>
<% end %>

<%= link_to 'Homepage', flights_path %>

app/views/flights/index.html.erb
<h1>Homepage</h1>
<h2>Search your flight</h2>
<p>Leave date field empty if you want to see all flights to your destinations</p>

<% flash.each do |type, msg| %>
  <div style="color:red">
    <%= msg %>
  </div>  
  <br>
<% end %>

<%= form_with(url: "/flights", method: "get", local: true) do |f| %>
  <p>
    Departure: <%= f.select(:departure_airport_id, @airport_options, selected: params[:departure_airport_id], prompt: 'From?') %> | <%#The 'selected' keeps the choice of the user inside the form after he presses the search button. without 'selected' the dropdown menu would reset to default values%>
    Destination: <%= f.select(:destination_airport_id, @airport_options, selected: params[:destination_airport_id], prompt: 'To?') %> | 
    Date: <%= f.date_field(:date, value: params[:date]) %><%#In this case 'value' is the equivalent of 'selected' in the other dropdowns%>
    <%= f.submit('Search flights') %>
  </p>
<% end %>
<br>

<%= form_with(url: 'bookings/new', method: 'get') do |f| %>
  <% if @available_flights %><%# This line of code prevents @available.flights.where to execute. When you load the page for the first time, @available_flights will not have any params, so it will be a nil class, which gives back an error. This line of code prevents the rest of the code to execute before the user inputs the params. It basically prevents the code to run until @available_flights returns true in the 'if' condition %>
    <% if @available_flights.where("date > ?", Time.now).any? %><%#the .where("date > ?", Time.now).any? indexes only the future flights, avoids all the past flights that will still be conserved in the database%>
      <h2>Available flights</h2>
      <% @available_flights.order('date').each do |flight| %>
        <p>
          <%= radio_button_tag(:flight_id, flight.id, required: true) %>
          From: <%= flight.departure_airport.code %> | 
          To: <%= flight.destination_airport.code %> | 
          Flight duration: <%= flight.flight_duration %> min | 
          Date: <%= flight.date.to_date %>
        </p>
      <% end %>
      <p>
        Number of seats: <%= select_tag(:seats, options_for_select((1..4).map { |i| [i,i] }), prompt: 'Select', required: 'true') %>
      </p>
      <%= f.submit 'Next' %>
      <%# I tried to make the seats appear for each flight result, but only the last seat form would submit the values, so I had to make a single seats dropdown %>
    <% else %>
      <p>No flights available</p>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsFlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/passengers/create.html.erb
<h1>Passengers#create</h1>
<p>Find me in app/views/passengers/create.html.erb</p>

app/views/passengers/new.html.erb
<h1>Passengers#new</h1>
<p>Find me in app/views/passengers/new.html.erb</p>